name: tbgs
description: musings of three bored graduate students
meta_description: ""
logo: false
paginate: 15
domain_name: 'http://remedialtensors.com/'
google_analytics: 'UA-XXXXXXXX-X'

# Gems
plugins: [jekyll-paginate]

