name: tbgs
description: musings of three bored graduate students
meta_description: ""

markdown: redcarpet
highlighter: rouge
logo: false
paginate: 15
domain_name: 'http://threeboredgraduatestudents.github.io/'
google_analytics: 'UA-XXXXXXXX-X'

# Gems
plugins: [jekyll-paginate]

